'use client';

import { useEffect, useState } from 'react';
import { useAuth } from '@/context/auth';
import { Header } from '@/components/layout/header';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/api/v1';

type ContentItem = {
  id: string;
  agentType: string;
  contentType: string;
  title?: string;
  content: string;
  createdAt: string;
};

const CONTENT_TYPE_LABELS: Record<string, string> = {
  social_post: 'Social Post',
  email_brief: 'Email Brief',
  blog_outline: 'Blog Outline',
  ad_copy: 'Ad Copy',
  content_calendar: 'Content Calendar',
  strategy: 'Strategy',
  campaign_plan: 'Campaign Plan',
  copy: 'Copy',
};

function agentBadgeVariant(agentType: string): 'default' | 'success' | 'warning' | 'error' | 'info' {
  const map: Record<string, 'default' | 'success' | 'warning' | 'error' | 'info'> = {
    CONTENT: 'info', SOCIAL: 'success', STRATEGY: 'warning', DIRECTOR: 'default',
  };
  return map[agentType] ?? 'default';
}

export default function ContentPage() {
  const { user, accessToken } = useAuth();
  const [items, setItems] = useState<ContentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<string>('all');
  const [expanded, setExpanded] = useState<string | null>(null);

  const companyId = user?.companyId ?? '';
  const token = accessToken ?? '';

  useEffect(() => {
    if (!companyId || !token) return;
    setLoading(true);
    const qs = filter !== 'all' ? `?contentType=${filter}` : '';
    fetch(`${API_BASE}/companies/${companyId}/content${qs}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then((r) => r.json())
      .then(setItems)
      .catch((err) => setError(err instanceof Error ? err.message : 'Failed to load content'))
      .finally(() => setLoading(false));
  }, [user, accessToken, filter]);

  async function handleDelete(id: string) {
    await fetch(`${API_BASE}/companies/${companyId}/content/${id}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    });
    setItems((prev) => prev.filter((i) => i.id !== id));
  }

  const contentTypes = [...new Set(items.map((i) => i.contentType))];

  return (
    <div className="flex flex-col">
      <Header title="Content Workspace" />

      <div className="flex-1 p-6">
        <p className="mb-4 text-sm text-gray-500">
          Content generated by AI agents — social posts, copy, strategies, and more.
        </p>

        <div className="mb-6 flex flex-wrap items-center gap-2 overflow-x-auto">
          <button
            onClick={() => setFilter('all')}
            className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${
              filter === 'all' ? 'bg-blue-600 text-white' : 'border border-gray-200 bg-white text-gray-600 hover:bg-gray-50'
            }`}
          >
            All
          </button>
          {contentTypes.map((ct) => (
            <button
              key={ct}
              onClick={() => setFilter(ct)}
              className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${
                filter === ct ? 'bg-blue-600 text-white' : 'border border-gray-200 bg-white text-gray-600 hover:bg-gray-50'
              }`}
            >
              {CONTENT_TYPE_LABELS[ct] ?? ct}
            </button>
          ))}
        </div>

        {error && (
          <div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
        )}

        {loading ? (
          <div className="space-y-3">
            {[1, 2, 3, 4].map((i) => <Skeleton key={i} className="h-24 w-full rounded-xl" />)}
          </div>
        ) : items.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <p className="text-4xl">✍️</p>
            <h3 className="mt-4 text-lg font-semibold text-gray-900">No content yet</h3>
            <p className="mt-2 max-w-sm text-sm text-gray-500">
              Ask the AI Director to generate content — social posts, email briefs, ad copy, and more will appear here.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {items.map((item) => (
              <Card key={item.id} className="overflow-hidden">
                <div
                  className="flex cursor-pointer items-start justify-between gap-4 p-4"
                  onClick={() => setExpanded(expanded === item.id ? null : item.id)}
                >
                  <div className="flex-1 min-w-0">
                    <div className="flex flex-wrap items-center gap-2 mb-1">
                      <p className="font-medium text-gray-900 truncate">
                        {item.title ?? CONTENT_TYPE_LABELS[item.contentType] ?? item.contentType}
                      </p>
                      <Badge variant={agentBadgeVariant(item.agentType)} className="text-[10px]">{item.agentType}</Badge>
                      <Badge variant="default" className="text-[10px]">{CONTENT_TYPE_LABELS[item.contentType] ?? item.contentType}</Badge>
                    </div>
                    <p className="text-xs text-gray-400">{new Date(item.createdAt).toLocaleString()}</p>
                    {expanded !== item.id && (
                      <p className="mt-1 line-clamp-2 text-sm text-gray-500">{item.content}</p>
                    )}
                  </div>
                  <div className="flex shrink-0 items-center gap-2">
                    <button
                      onClick={(e) => { e.stopPropagation(); handleDelete(item.id); }}
                      className="text-xs text-red-500 hover:text-red-700"
                    >
                      Delete
                    </button>
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      className={`h-4 w-4 text-gray-400 transition-transform ${expanded === item.id ? 'rotate-180' : ''}`}
                    >
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </div>
                </div>
                {expanded === item.id && (
                  <div className="border-t border-gray-100 bg-gray-50 px-4 py-3">
                    <pre className="whitespace-pre-wrap text-sm text-gray-700 font-sans">{item.content}</pre>
                    <button
                      onClick={() => navigator.clipboard.writeText(item.content)}
                      className="mt-2 text-xs text-blue-600 hover:text-blue-800"
                    >
                      Copy to clipboard
                    </button>
                  </div>
                )}
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
